### ISSUE TITLE
Make alltube server URL configurable

### ISSUE THREAD

**Issue by nodiscc** [Rudloff/alltube-firefox#1]
Hi, just discovered this project through https://github.com/rg3/youtube-dl/issues/469. Nice work, as always :+1:  How would I make the alltube server URL configurable in Firefox's addon prefs? (https://github.com/Rudloff/alltube-firefox/search?utf8=%E2%9C%93&q=alltubedownload)

**Comment by Rudloff** [comment]
Hello,

I have added a pref with the URL.
Can you please try this version: https://github.com/Rudloff/alltube-firefox/releases/tag/v0.3.2-beta
